chore: change \e to \033

diff --git a/format b/format
--- a/format
+++ b/format
@@ -2,9 +2,9 @@
 
 #Check if status is clean
 if output=$(git status --untracked-files=no --porcelain) && [ -z "$output" ]; then
-	printf "\033[1;32m[OK]\e[0m    Status is clean\n"
+	printf "\033[1;32m[OK]\033[0m    Status is clean\n"
 else
-	printf "\033[1;31m[ERR]\e[0m    Status is dirty. Quitting.\n"
+	printf "\033[1;31m[ERR]\033[0m    Status is dirty. Quitting.\n"
 	exit 1
 fi
 SRC_DIR="src"
@@ -19,20 +19,20 @@ SRC_BSP_DIR="src/bsp"
 hlpd_SOURCES=("$SRC_DIR"/*.c "$SRC_DIR"/*.h "$SRC_CORE_DIR"/*.c "$SRC_CORE_DIR"/*.h "$SRC_UTILS_DIR"/*.c "$SRC_UTILS_DIR"/*.h "$SRC_BUILD_NC_DIR"/*.c "$SRC_BUILD_NC_DIR"/*.h "$SRC_BUILD_NC_W64_DIR"/*.c "$SRC_BUILD_NC_W64_DIR"/*.h "$SRC_BUILD_RL_DIR"/*.c "$SRC_BUILD_RL_DIR"/*.h "$SRC_SER_DIR"/*.c "$SRC_SER_DIR"/*.h "$SRC_BSP_DIR"/*.c "$SRC_BSP_DIR"/*.h )
 CONFIG_FILE=".astylerc"
 
-printf "Running \033[1;34mastyle -s4 --style=linux\e[0m for all source files.\n"
+printf "Running \033[1;34mastyle -s4 --style=linux\033[0m for all source files.\n"
 for src_i in "${hlpd_SOURCES[@]}"; do {
     astyle --options="$CONFIG_FILE" $src_i >/dev/null
-    printf "Ran astyle on [\033[1;35m$src_i\e[0m], status was [\033[1;33m$?\e[0m]\n"
+    printf "Ran astyle on [\033[1;35m$src_i\033[0m], status was [\033[1;33m$?\033[0m]\n"
 }
 done
-printf "Removing all \033[1;34msrc/*.orig\e[0m files.\n"
+printf "Removing all \033[1;34msrc/*.orig\033[0m files.\n"
 for FILE in ${hlpd_SOURCES[@]}; do {
     if [[ -f "$FILE.orig" ]] ; then {
-      rm "$FILE.orig" && printf "Removed [\033[1;36m$FILE.orig\e[0m]\n"
+      rm "$FILE.orig" && printf "Removed [\033[1;36m$FILE.orig\033[0m]\n"
     } else {
-      printf "[INFO]    File [\033[1;33m$FILE.orig\e[0m] not found.\n"
+      printf "[INFO]    File [\033[1;33m$FILE.orig\033[0m] not found.\n"
     }
     fi
 }
 done
-printf "\033[1;33mDone.\e[0m\n"
+printf "\033[1;33mDone.\033[0m\n"
