feat: 1.4.21 Fight rebalance (#130)
### Changed

- Avoid usage of system()
- Try avoiding abs(), fabsf() in:
  - fight()
  - enemy_attack()
  - boss_fight()
  - boss_attack()
- Make hlpd-sim buildable for both ncurses and raylib configs
- Fix nc-w64 build
- Bump koliseo to 0.6.4
- Bump s4c to 0.5.3
- Bump invil to 0.2.31
- Bump amboso to 2.1.3

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -109,105 +109,105 @@ hlpd_save2l_SOURCES += src/utils/floors.c src/utils/rooms.c src/bsp/bsp.c src/ut
 endif
 
 ./anvil:
-	@echo -e "\033[1;35m[Makefile]\e[0m    Bootstrapping \"./anvil\":"
+	@echo -e "\033[1;35m[Makefile]\033[0m    Bootstrapping \"./anvil\":"
 	./scripts/bootstrap_anvil.sh $(ANVIL_IMPL)
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 ./src/anvil__helapordo.c: ./anvil
-	@echo -e "\033[1;34m[Makefile]\e[0m    Using \033[1;33mamboso\e[0m to generate [\033[1;34m./src/anvil__helapordo.c\e[0m and \033[1;34m./src/anvil__helapordo.h\e[0m] for [ \033[1;36m$(VERSION)\e[0m ]:"
+	@echo -e "\033[1;34m[Makefile]\033[0m    Using \033[1;33mamboso\033[0m to generate [\033[1;34m./src/anvil__helapordo.c\033[0m and \033[1;34m./src/anvil__helapordo.h\033[0m] for [ \033[1;36m$(VERSION)\033[0m ]:"
 	-./anvil -qXG ./src $(VERSION)
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 ./sprites4curses/src/s4c.o:
-	@echo -e "    \033[1;35mAM_CFLAGS\e[0m: [ \"\033[1;34m$(AM_CFLAGS)\e[0m\" ]"
-	@echo -en "\033[1;34m[Makefile]\e[0m    Building [\033[1;35m./sprites4curses/src/s4c.o\e[0m]:  "
+	@echo -e "    \033[1;35mAM_CFLAGS\033[0m: [ \"\033[1;34m$(AM_CFLAGS)\033[0m\" ]"
+	@echo -en "\033[1;34m[Makefile]\033[0m    Building [\033[1;35m./sprites4curses/src/s4c.o\033[0m]:  "
 	$(CCOMP) -c ./sprites4curses/src/s4c.c $(AM_CFLAGS) -o ./sprites4curses/src/s4c.o
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 ./koliseo/src/koliseo.o:
-	@echo -e "    \033[1;35mAM_CFLAGS\e[0m: [ \"\033[1;34m$(AM_CFLAGS)\e[0m\" ]"
-	@echo -en "\033[1;34m[Makefile]\e[0m    Building [\033[1;35m./koliseo/src/koliseo.o\e[0m]:  "
+	@echo -e "    \033[1;35mAM_CFLAGS\033[0m: [ \"\033[1;34m$(AM_CFLAGS)\033[0m\" ]"
+	@echo -en "\033[1;34m[Makefile]\033[0m    Building [\033[1;35m./koliseo/src/koliseo.o\033[0m]:  "
 	$(CCOMP) -c ./koliseo/src/koliseo.c $(AM_CFLAGS) -o ./koliseo/src/koliseo.o
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 ./src/palette.c:
-	@echo -en "\033[1;34m[Makefile]\e[0m    Using \033[1;33mpython3\e[0m to generate C [\033[1;34m./src/palette.c\e[0m and \033[1;34m./src/palette.h\e[0m] files from \033[1;35m[$(PALETTE_PATH)]:\e[0m  "
+	@echo -en "\033[1;34m[Makefile]\033[0m    Using \033[1;33mpython3\033[0m to generate C [\033[1;34m./src/palette.c\033[0m and \033[1;34m./src/palette.h\033[0m] files from \033[1;35m[$(PALETTE_PATH)]:\033[0m  "
 	python3 -m sprites4curses.s4c-scripts.s4c.core.palette C-impl $(PALETTE_PATH) .. > ./src/palette.c
 	python3 -m sprites4curses.s4c-scripts.s4c.core.palette C-header $(PALETTE_PATH) .. > ./src/palette.h
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 helapordo_core.o: $(helapordo_core_SOURCES:.c=.o)
-	@echo -e "\033[1;35m[Makefile]\e[0m    Linking \"$@\":"
+	@echo -e "\033[1;35m[Makefile]\033[0m    Linking \"$@\":"
 	$(CCOMP) -r -o $@ $^
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 # Build rule for object files
 %.o: %.c
-	@echo -e "    \033[1;35mAM_CFLAGS\e[0m: [ \"\033[1;34m$(AM_CFLAGS)\e[0m\" ]"
-	@echo -en "    [ $< ] -> [ \033[1;34m$@\e[0m ]:  "
+	@echo -e "    \033[1;35mAM_CFLAGS\033[0m: [ \"\033[1;34m$(AM_CFLAGS)\033[0m\" ]"
+	@echo -en "    [ $< ] -> [ \033[1;34m$@\033[0m ]:  "
 	$(CCOMP) -c $(CFLAGS) $(AM_CFLAGS) $< -o $@
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 # Build rule for the final binary
 $(TARGET): helapordo_core.o $(helapordo_SOURCES:.c=.o)
-	@echo -e "    \033[1;35mAM_CFLAGS\e[0m: [ \"\033[1;34m$(AM_CFLAGS)\e[0m\" ]"
-	@echo -e "    \033[1;35mAM_LDFLAGS\e[0m: [ \"\033[1;34m$(AM_LDFLAGS)\e[0m\" ]"
-	@echo -e "    \033[1;35mLDADD\e[0m: [ \"\033[1;34m$(LDADD)\e[0m\" ]"
-	@echo -en "\033[1;34m[Makefile]    Building [\033[1;35m $@ \033[1;34m]:\e[0m  "
+	@echo -e "    \033[1;35mAM_CFLAGS\033[0m: [ \"\033[1;34m$(AM_CFLAGS)\033[0m\" ]"
+	@echo -e "    \033[1;35mAM_LDFLAGS\033[0m: [ \"\033[1;34m$(AM_LDFLAGS)\033[0m\" ]"
+	@echo -e "    \033[1;35mLDADD\033[0m: [ \"\033[1;34m$(LDADD)\033[0m\" ]"
+	@echo -en "\033[1;34m[Makefile]    Building [\033[1;35m $@ \033[1;34m]:\033[0m  "
 	$(CCOMP) $(CFLAGS) $(AM_CFLAGS) helapordo_core.o $(helapordo_SOURCES:.c=.o) -o $@ $(LDADD) $(AM_LDFLAGS)
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 ./hlpd-save2l: helapordo_core.o $(hlpd_save2l_SOURCES:.c=.o)
-	@echo -en "\033[1;34m[Makefile]    Building [\033[1;35m $@ \033[1;34m]:\e[0m  "
+	@echo -en "\033[1;34m[Makefile]    Building [\033[1;35m $@ \033[1;34m]:\033[0m  "
 	$(CCOMP) $(CFLAGS) $(AM_CFLAGS) helapordo_core.o $(hlpd_save2l_SOURCES:.c=.o) -o $@ $(LDADD) $(AM_LDFLAGS)
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 ./hlpd-sim: helapordo_core.o scripts/sim/sim.c
-	@echo -en "\033[1;34m[Makefile]    Building [\033[1;35m $@ \033[1;34m]:\e[0m  "
-	$(CCOMP) helapordo_core.o scripts/sim/sim.c -o $@ -lm -l:libraylib.a -lX11 -lkoliseo
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -en "\033[1;34m[Makefile]    Building [\033[1;35m $@ \033[1;34m]:\033[0m  "
+	$(CCOMP) $(CFLAGS) $(AM_CFLAGS) helapordo_core.o scripts/sim/sim.c koliseo/src/koliseo.c -o $@ $(LDADD) $(AM_LDFLAGS)
+	@echo -e "\033[1;33mDone.\033[0m"
 
 # Targets for additional rules
 versioncheck:
 	@echo -en "Checking helapordo local version.\n\n    Expected ($(VERSION)),  got: ($(RUN_VERSION)).\n"
-	@test "$(VERSION)" = "$(RUN_VERSION)" || echo -en '\n    \033[1;31mFailed check for expected local version.\e[0m\n'
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@test "$(VERSION)" = "$(RUN_VERSION)" || echo -en '\n    \033[1;31mFailed check for expected local version.\033[0m\n'
+	@echo -e "\n\033[1;32mDone.\033[0m"
 
 const.k:
 	@echo -en "Building const.k test"
 	$(CCOMP) kazoj/bone/const.c -o kazoj/bone/const.k
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 
 const_rl.k:
 	@echo -en "Building const_rl.k test"
 	$(CCOMP) kazoj/bone/const_rl.c -o kazoj/bone/const_rl.k -lraylib -DS4C_RAYLIB_EXTENSION
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 
 anviltest: const.k const_rl.k
 	@echo -en "Running anvil tests.\n"
 	./anvil -tX
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 
 doc:
 	@echo -e "Using doxygen to create tex + html from $(VERSION) src/:    "
 	doxygen ./docs/helapordo.doxyfile
-	@echo -e "\n\033[1;33mDone.\e[0m\n"
+	@echo -e "\n\033[1;33mDone.\033[0m\n"
 	sleep 1
 	clear
 	@echo -e "Listing ./doxygen directory contents:\n"
 	ls -R ./doxygen
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 	@echo -e "\ncd to ./doxygen/latex and make tex into pdf:\n"
 	cd ./doxygen/latex ; make | grep "Output written"
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 	@echo -e "\ncd back to ../..:\n"
 	cd ../..
 	@echo -e "\nmv ./doxygen/latex/refman.pdf to (../../docs/docs.pdf) :\n"
 	mv ./doxygen/latex/refman.pdf ./docs/docs.pdf
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 	@echo -en "\nRemove ./doxygen/:    "
 	yes | rm -rd ./doxygen/
-	@echo -e "\n\033[1;32mDone.\e[0m"
+	@echo -e "\n\033[1;32mDone.\033[0m"
 
 pack: versioncheck
 	@echo -e "Packing helapordo:  make pack for $(VERSION)"
@@ -215,7 +215,7 @@ pack: versioncheck
 	./helapordo -v
 	@echo -e "\n    amboso version:"
 	./anvil -v
-	@echo -e "\033[1;32m[TREE] Prepping tree, pack for $(VERSION):\e[0m"
+	@echo -e "\033[1;32m[TREE] Prepping tree, pack for $(VERSION):\033[0m"
 	[[ -d ~/helapordo-local/ ]] || mkdir ~/helapordo-local
 	[[ -d ~/helapordo-local/share ]] || mkdir ~/helapordo-local/share
 	[[ -d ~/helapordo-local/share/$(PACK_NAME) ]] || mkdir ~/helapordo-local/share/$(PACK_NAME)
@@ -240,11 +240,11 @@ pack: versioncheck
 	[[ -d ~/helapordo-local/share/$(PACK_NAME)/ringabuf ]] || mkdir ~/helapordo-local/share/$(PACK_NAME)/ringabuf
 	[[ -d ~/helapordo-local/share/$(PACK_NAME)/ringabuf/src ]] || mkdir ~/helapordo-local/share/$(PACK_NAME)/ringabuf/src
 
-	@echo -e "\033[1;32m[TREE] Removing '~/helapordo-local/share/$(PACK_NAME).zip':\e[0m"
+	@echo -e "\033[1;32m[TREE] Removing '~/helapordo-local/share/$(PACK_NAME).zip':\033[0m"
 	touch ~/helapordo-local/share/$(PACK_NAME).zip
 	rm ~/helapordo-local/share/$(PACK_NAME).zip
-	@echo -e "\033[1;32m[TREE] Done.\e[0m"
-	@echo -e "\033[1;35m[PACK] Installing:\e[0m"
+	@echo -e "\033[1;32m[TREE] Done.\033[0m"
+	@echo -e "\033[1;35m[PACK] Installing:\033[0m"
 	install $(TARGET) ~/helapordo-local/share/$(PACK_NAME)
 	install ./LICENSE ~/helapordo-local/share/$(PACK_NAME)
 	install ./README.md ~/helapordo-local/share/$(PACK_NAME)
@@ -275,35 +275,35 @@ pack: versioncheck
 	install ./src/notifications/*.{c,h} ~/helapordo-local/share/$(PACK_NAME)/src/notifications/
 	install ./src/*.{c,h} ~/helapordo-local/share/$(PACK_NAME)/src/
 
-	@echo -e "\033[1;35m[PACK] Done.\e[0m"
-	@echo -e "\033[1;32m[ZIP] Compressing $(PACK_NAME):\e[0m"
+	@echo -e "\033[1;35m[PACK] Done.\033[0m"
+	@echo -e "\033[1;32m[ZIP] Compressing $(PACK_NAME):\033[0m"
 	cd ~/helapordo-local/share && zip -r $(PACK_NAME).zip ./$(PACK_NAME)
-	@echo -e "\033[1;33m[ZIP] Testing zip:\e[0m"
+	@echo -e "\033[1;33m[ZIP] Testing zip:\033[0m"
 	echo -e "\033[1;36m[UNZIP] Result:\n"
 	unzip -t ~/helapordo-local/share/$(PACK_NAME).zip | tail -n1
-	@echo -e "\033[1;32m[ZIP] Done.\e[0m"
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;32m[ZIP] Done.\033[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 run: helapordo
 	@echo -en "Running ./helapordo with debug flag.  "
 	./helapordo -d
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 install: helapordo
 	@echo -en "Installing helapordo $(VERSION):  "
 	./installer "-i" $(VERSION) $(TARGET_INSTALL_DIR) $(SOURCE_INSTALL_DIR) $(STATIC_DIR_NAME) $(SLOT1_DIR_NAME) $(SLOT2_DIR_NAME) $(SLOT3_DIR_NAME) $(INSTALLER_LOG_FILE)
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 do_alias:
 	@echo -en "Symlinking (~/helapordo-local/helapordo) to /usr/local/bin/helapordo:  "
 	@[[ -e /usr/local/bin/helapordo ]] || sudo ln -s ~/helapordo-local/helapordo /usr/local/bin/helapordo
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 uninstall:
 	@echo -en "Uninstalling helapordo:  "
 	[[ -d ~/helapordo-local ]] && rm -rd ~/helapordo-local
 	sudo rm /usr/local/bin/helapordo
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 clean:
 	@echo -en "Cleaning build artifacts:  "
@@ -327,7 +327,7 @@ clean:
 	-rm ./hlpd-sim
 	-rm ./scripts/save2l/*.o
 	-rm ./scripts/sim/*.o
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 cleanob:
 	@echo -en "Cleaning object build artifacts:  "
@@ -344,7 +344,7 @@ cleanob:
 	-rm src/release_data/*.o
 	-rm ./scripts/save2l/*.o
 	-rm ./scripts/sim/*.o
-	@echo -e "\033[1;33mDone.\e[0m"
+	@echo -e "\033[1;33mDone.\033[0m"
 
 # Default target (builds everything)
 all: ./src/palette.c ./koliseo/src/koliseo.o ./sprites4curses/src/s4c.o $(TARGET) ./hlpd-save2l
